[versions]
accessWiden = "2.2.0"
eyepatch = "1.0.2"
skanalyzer = "2.0.0-SNAPSHOT"

[libraries]
skanalyzer-core = { module = "me.glicz:skanalyzer-core", version.ref = "skanalyzer" }

build-accessWiden = { module = "me.glicz.access-widen:me.glicz.access-widen.gradle.plugin", version.ref = "accessWiden" }

[plugins]
eyepatch = { id = "me.glicz.eyepatch", version.ref = "eyepatch" }
